spring:
  application:
    name: resolutions
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: http://localhost:9000/oauth2/introspect
          client-id: resource-server
          client-secret: resolutions321
  datasource:
    url: jdbc:postgresql://localhost:5432/root
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    show-sql: true
  sql:
    init:
      mode: always
logging:
  level:
    org:
      hibernate:
        sql: DEBUG
        type: TRACE
        orm:
            jdbc:
              bind: TRACE
#      springframework.security: DEBUG
