spring:
  application:
    name: resolutions
  datasource:
    url: jdbc:postgresql://localhost:5432/root
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    show-sql: true
  sql:
    init:
      mode: always
logging.level.org.hibernate.sql: DEBUG